[package]
name = "roadrunner"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jwt-simple = "0.11.9"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
serde_json = "1.0"
